---
kind: pipeline
type: docker
name: python-3.7

steps:
- name: syntax-check
  image: codewaysa/python3-dev:3.7.7_20200718
  commands:
  - pylint -E hvac_ir

- name: PyLint
  image: codewaysa/python3-dev:3.7.7_20200718
  commands:
  - pylint  hvac_ir
  depends_on: [ 'syntax-check' ]
  failure: ignore

- name: isort
  image: codewaysa/python3-dev:3.7.7_20200718
  commands:
  - isort --check-only --diff --recursive  hvac_ir
  depends_on: [ 'syntax-check' ]
  failure: ignore

- name: black
  image: codewaysa/python3-dev:3.7.7_20200718
  commands:
  - black --target-version py37 -l 120 --diff --check  hvac_ir
  depends_on: [ 'syntax-check' ]
  failure: ignore

---
  kind: pipeline
  type: docker
  name: python-3.8

  steps:
  - name: syntax-check
    image: codewaysa/python3-dev:3.8.3_20200718
    commands:
    - pylint -E hvac_ir

  - name: PyLint
    image: codewaysa/python3-dev:3.8.3_20200718
    commands:
    - pylint  hvac_ir
    depends_on: [ 'syntax-check' ]
    failure: ignore

  - name: isort
    image: codewaysa/python3-dev:3.8.3_20200718
    commands:
    - isort --check-only --diff --recursive  hvac_ir
    depends_on: [ 'syntax-check' ]
    failure: ignore

  - name: black
    image: codewaysa/python3-dev:3.8.3_20200718
    commands:
    - black --target-version py38 -l 120 --diff --check  hvac_ir
    depends_on: [ 'syntax-check' ]
    failure: ignore
